# Generated by Django 4.2.7 on 2023-11-20 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appimob', '0002_alter_imovel_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='locatario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imovel_locado_locatario', to=settings.AUTH_USER_MODEL),
        ),
    ]
