# Generated by Django 4.2.7 on 2023-11-27 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appimob', '0003_alter_imovel_locatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis_possuidos', to='appimob.proprietario'),
        ),
    ]
